name: rocketbird
favicon: null
layout_spectrum: 0.73889
typography_spectrum: 0.38523
title: Rocket Bird Exploratory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfdeb'
    - '#b4b70e'
    - '#4cb4d7'
    - '#513d3c'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
