name: rocketbird
favicon: null
layout_spectrum: 0.9664688881020993
typography_spectrum: 0.3411597099620849
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.21317423041909933
  lightness: 0.26435020798817277
  saturation: 0.40386589034460485
  rhythmicContrast: 0.7046122467145324
purpose: []
