name: rocketbird
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27842
title: Rocket Bird Exploratory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121c11'
    - '#ffffff'
    - '#77a3c6'
    - '#635950'
    - '#f8cb7a'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
